services:
  php:
    container_name: php
    image: php:8-fpm-alpine

    volumes:
      - .:/var/www/html:ro

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 1337:80
    volumes:
      - .:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro


